#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034
START=96 #OpenWrt: 95 done
PNAME="autoauth.sh"
BasePath=/etc
TAG="autoauth"
# shellcheck disable=SC1091
. $BasePath/autoauth_common.sh

stop() {
    killall -q $PNAME
}
start() {
    stop
    LOG "$TAG" I "Starting $PNAME"
    /etc/$PNAME >/dev/null 2>&1 &
}
boot() {
    LOG "$TAG" I "autostart: HELLO!"
    /etc/$PNAME >/dev/null 2>&1 &
}

restart() {
    if ! (NET_AVAILABLE); then
        stop
        start
    else
        LOG "$TAG" I "The internet connection works! No need to restart $PNAME"
    fi
}
reload() {
    restart
}
