#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034
START=96 #OpenWrt: 95 done
PNAME="autoauth.sh"
BasePath=/etc
TAG="autoauth"
# shellcheck disable=SC1091
. $BasePath/autoauth_common.sh || exit 1

stop() {
    killall -q $PNAME
}
start() {
    stop
    LOG "$TAG" I "Starting $PNAME"
    $BasePath/$PNAME >/dev/null 2>&1 &
}
boot() {
    LOG "$TAG" I "autostart: HELLO!"
    $BasePath/$PNAME >/dev/null 2>&1 &
}

restart() {
    stop
    start
}
reload() {
    restart
}
