name: Shell checker

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses: actions/checkout@v3

    - name: Run ShellCheck
      id: check
      uses: ludeeus/action-shellcheck@master
